### ISSUE TITLE
Unhandled Promise Rejection: Error: Storage quota exceeded.

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4823]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

I'm unable to save the options:

```
Unhandled Promise Rejection: Error: Storage quota exceeded.
```

This happens for the second time this week, so it's probably happening to a lot of people

Possible improvements:

- Show error in UI via https://github.com/fregante/webext-options-sync/issues/27
- Keep at least 30% of the UI free of cache https://github.com/fregante/webext-storage-cache/issues/6
- Look at the cache contents and find the biggest offenders
- Add `unlimitedStorage` optional permission + _"your cache is filling up, best if you [allow more storage]"_ notice in the options page
	- or permanent permission if it doesn't cause the extension to be disabled

### Browser(s) used

Safari 15

**Comment by yakov116** [comment]
Does safari have a lower limit? To my knowledge I have never bumped into this issue.

**Comment by fregante** [comment]
Seems like it's still 5MB

<img width="217" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/134816581-bc80b176-af03-4124-836a-48c7a464ad0c.png">

**Comment by yakov116** [comment]
Is that in total? If I remember correctly chrome gives 2mb per extension.

**Comment by fregante** [comment]
> Is that in total? If I remember correctly chrome gives 2mb per extension.

All browsers give 5 with `storage` and more with `unlimitedStorage`. QUOTA is the total I think

**Comment by yakov116** [comment]
So maybe some other extention is using up your storage.
Side note: Looks like Firefox does not enforce this limit yet.

**Comment by jimeh** [comment]
I just had this issue on Safari after initial installation of Refined GitHub. My quota was reported as 5MB, and bytes in use was 11k.

Clicking the Clear Cache button however resolved the issue, and I could now add a PAT and disable specific refinements.

**Comment by fregante** [comment]
~sad bug noises~

**Comment by fregante** [comment]
My wish has been immediately granted and I'm hyper-confused.

- "bytes in use" reports the same value for both the local and sync storage
- the options are stored in the sync storage, but the cache is local… it should not affect the options
- used storage is 500k
- the smallest of storage calls fails

<img width="392" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/136084210-c80ec34b-c7cb-49d0-a09a-0331e72c1043.png">

As it becomes obvious from the screenshot, not only does Safari not support the `sync` storage (which was known), it also just points both storages to the same place, so unlike other browsers you can't store the same keys in 2 different storages independently.

So it's Safari being Safari.

**Comment by fregante** [comment]
<img width="521" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/136085258-b502e8db-6d73-48ee-bf1f-cea70e099359.png">


Max items: 512
Stored items: 847

![sponge-bob-mr-krabs](https://user-images.githubusercontent.com/1402241/136085172-ca81cdee-5036-44a7-83e6-2554988342f9.gif)

**Comment by fregante** [comment]
Safari is great. I just cleared the cache, I get the error almost immediately.

<img width="394" alt="Screen Shot 12 Redacted" src="https://user-images.githubusercontent.com/1402241/140032275-59a3e2fc-d25b-48fb-b230-ad8f31e6f24d.png">

**Comment by cheap-glitch** [comment]
I've been trying to fix this, but I can't get it to work on Firefox. Creating a rejected Promise does log an error in the console, but the handler seems to be completely ignored.

Or maybe the event isn't even dispatched? Some special rules for Web Extensions?

**Comment by fregante** [comment]
Are you creating the error in the extension itself or in the console? I suggest using Chrome for this stuff because Firefox’ consoles don't even have access to the content script

**Comment by fregante** [comment]
This has potentially been solved in Safari 15.2

![895FE636-6414-4BD5-986E-BE3E193B3DBC](https://user-images.githubusercontent.com/1402241/146136681-c2b908aa-d685-455c-9ce6-a8915d6da2cc.jpeg)


Also a new version of Refined GitHub should be released today for Safari so it clears the cache automatically when opening the options page.

**Comment by mainrs** [comment]
I really hate bumping the same issue, but I do encounter this in Firefox right now. It doesn't print the error message. But it still can't save the custom CSS, even if I hit the `Clear Cache` button before.

Should I open another issue?

**Comment by fregante** [comment]
Yes, new issue would be good. Can you open the options.html page on its own and look for console errors?
