### ISSUE TITLE
[GHE] Plugin disabled for no reason, and need to go to config page to enable

### ISSUE THREAD

**Issue by MonkeyLeeT** [refined-github/refined-github#6025]
### Description

This seems to only happen for GHE.

Every once in a while, mostly after a night, this plugin will disable itself, becoming this.

![image](https://user-images.githubusercontent.com/6754057/192872789-773ac9e0-95dc-4993-94a3-b60203f4e1d5.png)

And toggling that + refreshing will not restore functions (the check will be there but not working). I have to go to configuration page to toggle the extension completely to get it back to working.

![image](https://user-images.githubusercontent.com/6754057/192872996-51f22f0f-9f5e-49f9-94e2-7cbc446d4d64.png)

### How to replicate the issue

Haven't figured out the stable reproducing steps.

### Extension version

22.9.25

### Browser(s) used

Chrome

**Comment by busches** [comment]
Having the same issue, I haven't seen anything in the background page to indicate why it's happening. Figured it was a Chrome Policy coming from the Enterprise overloads.

**Comment by fregante** [comment]
The checkmark and the injection are two completely separate and unrelated features, they both just ask the browser whether the extension has permission to the current domain. 

My guess is that this has to do with the background page unloading. I wonder if https://github.com/fregante/webext-dynamic-content-scripts/pull/38 will fix it.

**Comment by busches** [comment]
The domain is never unselected for me, the extension just stops working and disabling/enabling it fixes it. I wouldn't be surprised if it's Chrome killing the extension too as the computer is low on memory. Any logging or anything I could find to narrow it down?

**Comment by fregante** [comment]
No I think this is just due to the API I used: https://github.com/fregante/content-scripts-register-polyfill/issues/11#issuecomment-1164527771

The linked PR should fix it, but I haven't had the time to merge it yet. This is actually a good opportunity to see if it works well for Refined GitHub. I'll try to merge it this week and publish a RG release.

**Comment by MonkeyLeeT** [comment]
Sorry for reopening this, but it's still happening and during the day time so no sleep or anything. Same symptom that enable check will be off, and toggling it won't help until I turn off/on the extension. The fix did help for over-night disabling.

I did notice this usually happen if I click certain GHE link from my email notifications. Not sure if it's related.

And no console logging about errors. Is there way to find more what's happening behind the scene?

**Comment by fregante** [comment]
Thanks for reporting back. This issue can't be fixed until:

- https://github.com/refined-github/refined-github/issues/5531

Because the API I'm using for GHE support isn't compatible with "event pages" in Manifest v2

**Comment by fregante** [comment]
Does anyone using Firefox can report back on the reliability of the injection? I think it should already work there because Firefox uses the new API even on MV2

**Comment by fregante** [comment]
Solution: set `background.persistent = true` via `dot-json` in the release.yml file. 

We need it to be `false` in Safari and I think it’s easier to set it only when publishing it to the Chrome and Firefox stores. 

It will eventually be fully fixed as part of:

- https://github.com/refined-github/refined-github/issues/5531
