### ISSUE TITLE
Creating feature for the first time

### ISSUE THREAD

**Issue by iGabyTM** [refined-github/refined-github#6606]
I'm trying to make a feature that highlights `// TODO` comments and I really can't get it to run :(
The code inside `init()` is not running (the console.log is not printed) and I have this warning in console
> `DevTools failed to load source map: Could not load content for chrome-extension://dehmkhkfkicaaafgjnhpmlocdafjedmh/index.js.map: System error: net::ERR_BLOCKED_BY_CLIENT`
  
Here's the code: https://github.com/iGabyTM/refined-github/tree/feature/highlight-todo-comments

**Comment by fregante** [comment]
Hello, have you tried restarting webpack? I noticed this issue recently, #6597 should fix it.

**Comment by iGabyTM** [comment]
I've followed the steps from contributing.md, how do I do that?

**Comment by iGabyTM** [comment]
Yes, that one is appearing in console, but not the one inside `init()`.
I've tried to run both commands again (`npm run watch` and `npx web-ext run --target=chromium`) but with no luck

**Comment by fregante** [comment]
It's possible that you _must_ include the feature in the readme, even temporarily. Can you check that? The readme is used to create a list of features to enable at runtime, so if it's not found there I think it's not run. We should fix that

**Comment by iGabyTM** [comment]
I've added it to the readme and the total amount of features was increased from 208 to 209, though I can not find it in the list, but it is still not working.

**Comment by fregante** [comment]
After that, you have to restart the build/watch

**Comment by iGabyTM** [comment]
Yes I now add the extension manually via "load unpacked" and use `npm run build` to build it, still no luck.

**Comment by iGabyTM** [comment]
This is the URL I use for testing btw https://github.com/iGabyTM/arcane-vouchers/blob/72f194e8866ce363ed93a827ccd058c60909a874/plugin/src/main/kotlin/me/gabytm/minecraft/arcanevouchers/api/events/VoucherRedeemEvent.kt#L9

**Comment by fregante** [comment]
You're missing a semi-colon:

https://github.com/iGabyTM/refined-github/blob/38514bc56affca0b639979283c2a9fe8ea882b5f/source/refined-github.ts#L217

It's really required 😅

**Comment by iGabyTM** [comment]
Oh wow.. it was really that

**Comment by iGabyTM** [comment]
![image](https://user-images.githubusercontent.com/32105478/236159839-fff11091-957c-4bb1-b380-5c56ecab85a8.png)
Damn it is finally working. Any idea why it modifies the elements only on the first load of the extension? Like, if I refresh the page, the `select.all()` acts like nothing is there to find

**Comment by fregante** [comment]
GitHub’s UI is increasingly dynamic. The issue you're seeing has likely the same source as:

- https://github.com/refined-github/refined-github/issues/5870

I suggest using `observe()` instead of `select.all()` so it becomes a "live selector"
