### ISSUE TITLE
`update-pr-from-base-branch`: update branch button no longer visible

### ISSUE THREAD

**Issue by jtvdez** [refined-github/refined-github#8616]
### Description

The update branch button no longer appears on PR's that are behind the target branch. Number of commits behind also no longer displayed. Confirmed with a colleague that they are also experiencing it.

<img width="923" height="1008" alt="Image" src="https://github.com/user-attachments/assets/cb9c3a7f-55b8-402c-8c22-ff6db0287325" />

### How to replicate the issue + URL

* Open a pull request
* Make sure branch is out of sync with head
* note lack of button or info on how many commits behind the base branch it is

https://github.com/grafana/grafana/pull/109088

### Extension version

25.8.4

### Browser(s) used

Chrome

### Token ⚠️

- [x] I set a token in the options page. I understand that some features require a token to work.

**Comment by jtvdez** [comment]
I've noticed that sometimes when I switch to a tab with a PR open the extension tries to tell me the info for like half a second before reverting to the view I've attached. I'll try to get a screengrab but it doesn't happen with any regularity

**Comment by jtvdez** [comment]
I wasn't able to record it so all I have is a screenshot, but it does look like the extension is trying and then something happens causing it to not stay persistently on the page

<img width="951" height="604" alt="Image" src="https://github.com/user-attachments/assets/56fb5736-bf62-4e96-8b3e-105b456058c6" />

**Comment by fregante** [comment]
Thanks for the report! The issue is described here: https://github.com/refined-github/refined-github/pull/8594#discussion_r2244799328

In short, it's because we add the buttons and React updates the UI. The button is removed, but our "seen" class is not, leading Refined GitHub to think it already acted on it. 

There's no easy solution:

- we observe a different element (one that is removed during this UI update)
- we move the items elsewhere

The mergeability box is the worst place to work on because it has so much variation, but it is the right place for these features. 

The simplest solution would be to always add one more row in that box so that it's not removed by React's updates, but that means it will cause content shift (the buttons/textarea below will move down maybe while you're about to click them). This is the last resort.

**Comment by fregante** [comment]
@SunsetTechuila have you experienced this in the past year?

**Comment by fregante** [comment]
If you experience this in 2026, leave a comment with:

- current version
- current browser
- screenshot (MUST)

After 2026, open a new issue

**Comment by SunsetTechuila** [comment]
Everything described in this issue should be fixed by #9366

**Comment by albertpmz** [comment]
I'm still experiencing this in 2026.

- Current version: v26.6.7
- Current browser: Google Chrome 149.0.7827.200

<img width="886" height="423" alt="Image" src="https://github.com/user-attachments/assets/71d441ec-e1ab-4b0f-ba15-35d281b20f29" />
